version: 2.1

jobs:
  build:
    docker:
      - image: bash:5.0.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./main.sh

workflows:
  test:
    jobs:
      - build
